# Data Preprocessing

In [3]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('../data/raw/quikr_car.csv')
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
df.shape

(892, 6)

In [6]:
df.duplicated().sum()
# There are duplicates in our data we have to manage that
# so here it show there are 94 duplicates value present in our dataset

np.int64(94)

In [7]:
df.duplicated(subset=['name','company','year','Price','kms_driven','fuel_type']).value_counts()
# it shows that 94 rows are completly duplicate
# That means all the columns values are same

False    798
True      94
Name: count, dtype: int64

In [8]:
df[df.duplicated()]

,name,company,year,Price,kms_driven,fuel_type
14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
15,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
20,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
24,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
25,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
...,...,...,...,...,...,...
626,Tata Sumo Gold EX BS IV,Tata,2012,"2,10,000","75,000 kms",Diesel
641,Maruti Suzuki Swift VDi BS IV,Maruti,2012,"2,80,000","48,006 kms",Diesel
727,Mahindra Scorpio S4,Mahindra,2015,"8,65,000","30,000 kms",Diesel
861,Hyundai Getz Prime 1.3 GLX,Hyundai,2009,"1,15,000","20,000 kms",Petrol
880,Maruti Suzuki Swift Dzire Tour VDi,Maruti,2009,"2,50,000","51,000 kms",Diesel

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(798, 6)

In [11]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    50
fuel_type     53
dtype: int64

In [12]:
missing_val_dict = {
    'Unique_value': df.nunique(),
    'Missing_value': df.isnull().sum(),
    'Missing_value_percent': (df.isnull().sum() / df.shape[0]) * 100
}

missing_val_dict = pd.DataFrame(missing_val_dict)
missing_val_dict

            Unique_value  Missing_value  Missing_value_percent
name                 525              0               0.000000
company               48              0               0.000000
year                  61              0               0.000000
Price                274              0               0.000000
kms_driven           258             50               6.265664
fuel_type              3             53               6.641604

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 798 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        798 non-null    object
 1   company     798 non-null    object
 2   year        798 non-null    object
 3   Price       798 non-null    object
 4   kms_driven  748 non-null    object
 5   fuel_type   745 non-null    object
dtypes: object(6)
memory usage: 43.6+ KB

## Analysing And Cleaning the data column wise

### Taking name column

In [14]:
df['name'].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P',
       'I want to sell my car Tata Zest', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Maruti Suzuki Alto 800 Lxi', 'Hindustan Motors Ambassador',
       'Toyota Corolla Altis 1.8 GL', 'Toyota Corolla Altis 1.8 J',
       'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Datsun Redi GO T O',
       'Maruti Suzuki Swift RS VDI', 'Fiat Punto Emotion 1.2',
       'Hyundai i10 Sportz 1.2', 'Chevrolet Beat LT Opt Diesel',
       'Chevrolet Beat LS Diesel', 'Tata Indigo CS',
       'Maruti Suzuki Swift VDi', 'Hyundai Eon Era Plus',
       'Mahindra XUV500', 'Ford Fiesta', 'Maruti Suzuki Wagon R',
       'Hyundai i20', 'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX',
       'Commercial , DZire LDI, 2016, for sale', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Tata indigo ecs LX, 201', 'Mahindra Scorpio SLX',
       'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII', 'MARUTI SUZUKI DESI',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX', 'Yama',
       'Maruti Suzuki Swift LDi', 'Mahindra TUV300 T4 Plus',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III',
       'Tata Indica eV2 LS', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'selling car Ta',
       'Honda City 1.5 V MT Exclusive', 'Chevrolet Spark LT 1.0 Airbag',
       'Tata Indigo eCS VX CR4 BS IV', 'Tata Zest 90',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Maruti Suzuki Swift Dzire car',
       'Hyundai Verna 1.4 VTVT', 'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Swift Dzire Tour (Gat',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'URJE',
       'Hyundai Santro Xing GLS', 'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Swift Dzire Tour 27 Dec 2016 Regis', 'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Used Commercial Maruti Omn',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Wagon R Select Variant',
       'Tata Nano Lx BSIV', 'Jaguar XE XE Portfolio',
       'Hyundai Xcent S 1.2', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Toyota Innova 2.0 V',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Hyun', 'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Datsun Go Plus T O',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Commercial Chevrolet Sail Hatchback ca', 'Hyundai Xcent SX 1.2',
       'Tata Nano LX Special Edition', 'Commercial Car Ta',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Used bt new conditions ta', 'Renault Kwid 1.0', 'Sale tata',
       'Tata Venture EX 8 STR', 'Maruti Suzuki Swift Dzire Tour LXi',
       'Maruti Suzuki Alto LX BSII', 'Skoda Octavia Classic 1.9 TDI MT',
       'Maruti Suzuki Omni LPG BS IV', 'Tata Sumo Gold EX BS IV',
       'Tata indigo 2017 top model..', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Tata indigo', 'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV',
       'very good condition tata bolts are av', 'Toyota Innova 2.0 G4',
       'Sale Hyundai xcent commerc', 'Maruti Suzuki Swift VDi ABS',
       'Hyundai Elite i20 Asta 1.2', 'Volkswagen Polo Trendline 1.5L D',
       'Toyota Etios Liva Diesel', 'Maruti Suzuki Ciaz ZXi Plus RS',
       'Hyundai Elantra 1.8 S', 'Ford EcoSport Trend 1.5L Ti VCT',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI',
       'I want to sell my commercial car due t',
       'Hyundai Santro AE GLS Audio',
       'i want sale my car.no emi....uber atta', 'Tata ZEST 6 month old',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'MARUTI SUZUKI ERTIGA F', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ', 'Tata Nexon', 'Tata',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       '2012 Tata Sumo Gold f', 'Mahindra Xylo E8 BS IV',
       'Well mentained Tata Sumo',
       'all paper updated tata indica v2 and u',
       'Maruti Ertiga showroom condition with',
       '7 SEATER MAHINDRA BOLERO IN VERY GOOD', '9 SEATER MAHINDRA BOL',
       'scratch less Tata I', 'Maruti Suzuki swift dzire for sale in',
       'Commercial Chevrolet beat for sale in',
       'urgent sell my Mahindra qu', 'Tata Sumo Gold FX BSIII',
       'sell my car Maruti Suzuki Swif',
       'Maruti Suzuki Swift Dzire good car fo', 'Hyunda',
       'Commercial Maruti Suzuki Alto Lxi 800', 'urgent sale Ta',
       'Maruti Suzuki Alto vxi t', 'tata', 'TATA INDI', 'Hyundai Creta',
       'Tata Bolt XM Petrol', 'Hyundai Venue', 'Maruti Suzuki Ritz',
       'Renault Lodgy', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Any type car avaiabel hare...comercica', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS',
       'Volkswagen Vento Highline Plus 1.5 Diesel', 'Tata Manza',
       'Toyota Innova 2.0 G1 Petrol 8seater', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Alto 800 Select Variant',
       'Maruti Suzuki Ritz VXI ABS', 'tata zest 2017 f',
       'Tata Indica V2 DLE BS III', 'Ta', 'Tata Zest XM Diesel',
       'Honda Amaze 1.2 E i VTEC', 'Chevrolet Sail 1.2 LT ABS'],
      dtype=object)

In [15]:
df.shape

(798, 6)

In [16]:
df = df[~(df['name'].str.startswith('Any')| df['name'].str.startswith('I') | df['name'].str.startswith('i') | df['name'].str.startswith('Commercial') | df['name'].str.endswith('Ta') | df['name'].str.startswith('all'))]

In [17]:
df.shape

(785, 6)

In [18]:
df['name']= df['name'].str.split().str.slice(start=0, stop=3).str.join(' ')
df['name']

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
2          Maruti Suzuki Alto
3           Hyundai Grand i10
4      Ford EcoSport Titanium
                ...
886      Toyota Corolla Altis
888              Tata Zest XM
889        Mahindra Quanto C8
890           Honda Amaze 1.2
891        Chevrolet Sail 1.2
Name: name, Length: 785, dtype: object

In [19]:
df.name.unique()

array(['Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Maruti Suzuki Alto',
       'Hyundai Grand i10', 'Ford EcoSport Titanium', 'Ford Figo',
       'Hyundai Eon', 'Ford EcoSport Ambiente', 'Skoda Fabia Classic',
       'Maruti Suzuki Stingray', 'Hyundai Elite i20',
       'Mahindra Scorpio SLE', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Hyundai i20 Sportz',
       'Maruti Suzuki Vitara', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Toyota Innova 2.0',
       'Renault Lodgy 85', 'Skoda Yeti Ambition', 'Maruti Suzuki Baleno',
       'Renault Duster 110', 'Renault Duster 85', 'Honda City 1.5',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5',
       'Honda City', 'Datsun Redi GO', 'Maruti Suzuki SX4',
       'Mitsubishi Pajero Sport', 'Honda City ZX', 'Tata Indigo eCS',
       'Volkswagen Polo Highline', 'Chevrolet Spark LS',
       'Renault Duster 110PS', 'Mini Cooper S', 'Skoda Fabia 1.2L',
       'Renault Duster', 'Mahindra Scorpio S4', 'Mahindra Scorpio VLX',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline', 'Hyundai i20 Magna',
       'Toyota Corolla Altis', 'Hyundai Verna Transform', 'BMW 3 Series',
       'Maruti Suzuki A', 'Toyota Etios GD', 'Ford Figo Diesel',
       'Chevrolet Beat LT', 'BMW 7 Series', 'Mahindra XUV500 W8',
       'Hyundai i10 Magna', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Ertiga', 'Honda Amaze 1.2', 'Hyundai i20 Asta',
       'Maruti Suzuki Eeco', 'Maruti Suzuki Esteem', 'Maruti Suzuki Ritz',
       'Toyota Etios Liva', 'Chevrolet Spark', 'Nissan Micra XV',
       'Chevrolet Beat', 'Toyota Corolla', 'Ford EcoSport Trend',
       'Tata Indica V2', 'Hindustan Motors Ambassador',
       'Toyota Innova 2.5', 'Volkswagen Jetta Highline',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Renault Kwid',
       'Chevrolet Spark LT', 'Fiat Punto Emotion', 'Hyundai i10 Sportz',
       'Chevrolet Beat LS', 'Tata Indigo CS', 'Hyundai Eon Era',
       'Mahindra XUV500', 'Ford Fiesta', 'Hyundai i20',
       'Hyundai Fluidic Verna', 'Fiat Petra ELX', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Zen', 'Hyundai Creta 1.6', 'Tata indigo ecs',
       'Mahindra Scorpio SLX', 'Tata Nano Cx', 'Tata Sumo Victa',
       'MARUTI SUZUKI DESI', 'Volkswagen Passat Diesel',
       'Renault Scala RxL', 'Hyundai i20 Active', 'Mahindra Xylo E4',
       'Mahindra Jeep MM', 'Mahindra Bolero SLE', 'Force Motors Force',
       'Toyota Etios', 'Honda City VX', 'Mahindra Thar CRDe',
       'Audi A4 1.8', 'Mercedes Benz GLA', 'Land Rover Freelander',
       'Renault Kwid RXT', 'Tata Aria Pleasure', 'Mercedes Benz B',
       'Datsun GO T', 'Honda Jazz VX', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold', 'Chevrolet Enjoy 1.4',
       'Nissan Terrano XL', 'Maruti Suzuki Maruti', 'Renault Kwid 1.0',
       'Hyundai Accent GLX', 'Yama', 'Mahindra TUV300 T4',
       'Tata Indica eV2', 'Honda Accord', 'Mahindra Scorpio 2.6',
       'Honda Mobilio', 'Skoda Laura', 'Tata Manza Aura',
       'Chevrolet Sail UVA', 'Audi A4 2.0', 'Hyundai Elantra SX',
       'Mahindra KUV100 K8', 'Hyundai i10', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Mahindra Bolero Power',
       'Tata Zest 90', 'Skoda Rapid Elegance', 'Tata Vista Quadrajet',
       'Chevrolet Beat Diesel', 'Hyundai Verna 1.4',
       'Maruti Suzuki Versa', 'Tata Indigo LX', 'Volkswagen Vento Konekt',
       'Mercedes Benz C', 'URJE', 'Maruti Suzuki Omni',
       'Hyundai Sonata Transform', 'Honda Jazz S', 'Mahindra Scorpio W',
       'Swift Dzire Tour', 'Honda Brio V', 'Mahindra TUV300 T8',
       'Nissan X Trail', 'Ford Ikon 1.3', 'Toyota Fortuner 3.0',
       'Tata Manza ELAN', 'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A', 'Tata Indigo LS', 'Used Commercial Maruti',
       'Hyundai Verna 1.6', 'BMW 5 Series', 'Skoda Superb 1.8',
       'Audi Q3 2.0', 'Ford Figo Duratorq', 'Mahindra Logan Diesel',
       'Tata Nano GenX', 'Honda City SV', 'Ford Figo Petrol',
       'Toyota Corolla H2', 'Hyundai Xcent Base',
       'Hyundai Accent Executive', 'Tata Zest XE', 'Mahindra XUV500 W6',
       'Tata Tigor Revotron', 'Maruti Suzuki 800', 'Honda Mobilio S',
       'Tata Indica', 'Honda Brio VX', 'Tata Nano Lx', 'Jaguar XE XE',
       'Hyundai Xcent S', 'Hyundai Eon Magna', 'Hyundai Eon D',
       'Maruti Suzuki Estilo', 'Mahindra Scorpio Vlx',
       'Mitsubishi Lancer 1.8', 'Ford Fiesta SXi', 'Audi A6 2.0',
       'Hyundai Getz Prime', 'Hyundai Santro', 'Chevrolet Beat PS',
       'BMW X1 xDrive20d', 'Tata Nano', 'Chevrolet Cruze LTZ', 'Hyun',
       'Mahindra XUV500 W10', 'Hyundai Accent GLE', 'Force Motors One',
       'Datsun Go Plus', 'Chevrolet Spark 1.0', 'Renault Duster 85PS',
       'Chevrolet Enjoy', 'Jeep Wrangler Unlimited', 'Hyundai Verna VGT',
       'Maruti Suzuki Celerio', 'Tata Zest Quadrajet', 'Hyundai i10 Era',
       'Tata Indigo Marina', 'Hyundai Xcent SX', 'Tata Nano LX',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua',
       'Used bt new', 'Sale tata', 'Tata Venture EX',
       'Skoda Octavia Classic', 'Tata indigo 2017', 'Ford Ikon 1.6',
       'Tata indigo', 'Nissan Sunny XL', 'very good condition',
       'Sale Hyundai xcent', 'Volkswagen Polo Trendline',
       'Hyundai Elantra 1.8', 'Jaguar XF 2.2', 'Audi Q5 2.0',
       'BMW X1 sDrive20d', 'Maruti Suzuki S',
       'Volkswagen Vento Comfortline', 'Mahindra KUV100',
       'Volkswagen Jetta Comfortline', 'Volvo S80 Summum', 'BMW X1',
       'Renault Duster RxL', 'Honda WR V', 'Mahindra Scorpio LX',
       'Audi A3 Cabriolet', 'Hyundai Santro AE', 'Tata ZEST 6',
       'Mahindra Xylo D2', 'Hyundai Getz GLE', 'Nissan Micra XL',
       'MARUTI SUZUKI ERTIGA', 'Chevrolet Tavera LS',
       'Tata Tiago Revotron', 'Tata Tiago Revotorq', 'Tata Nexon', 'Tata',
       'Ford Fusion 1.4', 'Fiat Linea Emotion', 'Tata Sumo Grande',
       'Volkswagen Polo Highline1.2L', '2012 Tata Sumo',
       'Well mentained Tata', 'Maruti Ertiga showroom',
       '7 SEATER MAHINDRA', '9 SEATER MAHINDRA', 'scratch less Tata',
       'Maruti Suzuki swift', 'urgent sell my', 'sell my car', 'Hyunda',
       'tata', 'TATA INDI', 'Hyundai Creta', 'Tata Bolt XM',
       'Hyundai Venue', 'Renault Lodgy', 'Ford Endeavor 4x4',
       'Mahindra Logan', 'Chevrolet Sail 1.2', 'Tata Manza',
       'Toyota Etios G', 'Toyota Qualis', 'Mahindra Quanto C4',
       'Hyundai i20 Select', 'Hyundai Getz', 'Skoda Fabia',
       'tata zest 2017', 'Tata Zest XM'], dtype=object)

#### It Still contain some rubbish names so try to find those names

In [20]:
df[~df['name'].str.startswith(('Jaguar', 'Volvo', 'Land', 'Jeep', 'Force', 'Mercedes', 'Mini','Mitsubishi', 'Datsun','Fiat','Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Renault', 'Honda', 'Chevrolet', 'Volkswagen', 'Toyota', 'BMW', 'Hindustan', 'Nissan', 'Tata'))]

                       name  company  year          Price kms_driven fuel_type
206      MARUTI SUZUKI DESI   MARUTI  TOUR       4,00,000        NaN       NaN
294                    Yama   Yamaha  r 15         55,000        NaN       NaN
401                    URJE   URJENT  SELL       1,80,000        NaN       NaN
414        Swift Dzire Tour    Swift  tion       3,70,000        NaN       NaN
441  Used Commercial Maruti     Used  arry       1,50,000        NaN       NaN
560                    Hyun  Hyundai   Eon  Ask For Price        NaN       NaN
608             tata Indica     tata  sale       1,30,000        NaN       NaN
614             Used bt new     Used  Zest       2,55,000        NaN       NaN
616               Sale tata     Sale  ture       1,00,000        NaN       NaN
643     very good condition     very  able       2,00,000        NaN       NaN
645      Sale Hyundai xcent     Sale   no.  Ask For Price        NaN       NaN
758    MARUTI SUZUKI ERTIGA   MARUTI  SALE       6,50,000        NaN       NaN
792          2012 Tata Sumo     2012  sell       2,50,000        NaN       NaN
795     Well mentained Tata     Well  d Ex       3,80,000        NaN       NaN
798       7 SEATER MAHINDRA        7  D...  Ask For Price        NaN       NaN
799       9 SEATER MAHINDRA        9  , Ac  Ask For Price        NaN       NaN
800       scratch less Tata  scratch  go .       1,40,000        NaN       NaN
803          urgent sell my   urgent  o c4       3,50,000        NaN       NaN
805             sell my car     sell  zire       3,00,000        NaN       NaN
807                  Hyunda  Hyundai  cent  Ask For Price        NaN       NaN
811                    tata     tata  t xe  Ask For Price        NaN       NaN
812               TATA INDI     TATA   EV2       1,10,000        NaN       NaN
884          tata zest 2017     tata  sale       4,50,000        NaN       NaN

In [21]:
df = df[df['name'].str.startswith(('Jaguar', 'Volvo', 'Land', 'Jeep', 'Force', 'Mercedes', 'Mini','Mitsubishi', 'Datsun','Fiat','Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Renault', 'Honda', 'Chevrolet', 'Volkswagen', 'Toyota', 'BMW', 'Hindustan', 'Nissan', 'Tata'))]

In [22]:
df['name'].unique()

array(['Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Maruti Suzuki Alto',
       'Hyundai Grand i10', 'Ford EcoSport Titanium', 'Ford Figo',
       'Hyundai Eon', 'Ford EcoSport Ambiente', 'Skoda Fabia Classic',
       'Maruti Suzuki Stingray', 'Hyundai Elite i20',
       'Mahindra Scorpio SLE', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Hyundai i20 Sportz',
       'Maruti Suzuki Vitara', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Toyota Innova 2.0',
       'Renault Lodgy 85', 'Skoda Yeti Ambition', 'Maruti Suzuki Baleno',
       'Renault Duster 110', 'Renault Duster 85', 'Honda City 1.5',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5',
       'Honda City', 'Datsun Redi GO', 'Maruti Suzuki SX4',
       'Mitsubishi Pajero Sport', 'Honda City ZX', 'Tata Indigo eCS',
       'Volkswagen Polo Highline', 'Chevrolet Spark LS',
       'Renault Duster 110PS', 'Mini Cooper S', 'Skoda Fabia 1.2L',
       'Renault Duster', 'Mahindra Scorpio S4', 'Mahindra Scorpio VLX',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline', 'Hyundai i20 Magna',
       'Toyota Corolla Altis', 'Hyundai Verna Transform', 'BMW 3 Series',
       'Maruti Suzuki A', 'Toyota Etios GD', 'Ford Figo Diesel',
       'Chevrolet Beat LT', 'BMW 7 Series', 'Mahindra XUV500 W8',
       'Hyundai i10 Magna', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Ertiga', 'Honda Amaze 1.2', 'Hyundai i20 Asta',
       'Maruti Suzuki Eeco', 'Maruti Suzuki Esteem', 'Maruti Suzuki Ritz',
       'Toyota Etios Liva', 'Chevrolet Spark', 'Nissan Micra XV',
       'Chevrolet Beat', 'Toyota Corolla', 'Ford EcoSport Trend',
       'Tata Indica V2', 'Hindustan Motors Ambassador',
       'Toyota Innova 2.5', 'Volkswagen Jetta Highline',
       'Volkswagen Polo Comfortline', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Renault Kwid',
       'Chevrolet Spark LT', 'Fiat Punto Emotion', 'Hyundai i10 Sportz',
       'Chevrolet Beat LS', 'Tata Indigo CS', 'Hyundai Eon Era',
       'Mahindra XUV500', 'Ford Fiesta', 'Hyundai i20',
       'Hyundai Fluidic Verna', 'Fiat Petra ELX', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Zen', 'Hyundai Creta 1.6', 'Tata indigo ecs',
       'Mahindra Scorpio SLX', 'Tata Nano Cx', 'Tata Sumo Victa',
       'Volkswagen Passat Diesel', 'Renault Scala RxL',
       'Hyundai i20 Active', 'Mahindra Xylo E4', 'Mahindra Jeep MM',
       'Mahindra Bolero SLE', 'Force Motors Force', 'Toyota Etios',
       'Honda City VX', 'Mahindra Thar CRDe', 'Audi A4 1.8',
       'Mercedes Benz GLA', 'Land Rover Freelander', 'Renault Kwid RXT',
       'Tata Aria Pleasure', 'Mercedes Benz B', 'Datsun GO T',
       'Honda Jazz VX', 'Chevrolet Tavera Neo', 'Hyundai Eon Sportz',
       'Tata Sumo Gold', 'Chevrolet Enjoy 1.4', 'Nissan Terrano XL',
       'Maruti Suzuki Maruti', 'Renault Kwid 1.0', 'Hyundai Accent GLX',
       'Mahindra TUV300 T4', 'Tata Indica eV2', 'Honda Accord',
       'Mahindra Scorpio 2.6', 'Honda Mobilio', 'Skoda Laura',
       'Tata Manza Aura', 'Chevrolet Sail UVA', 'Audi A4 2.0',
       'Hyundai Elantra SX', 'Mahindra KUV100 K8', 'Hyundai i10',
       'Hyundai Accent', 'Hyundai Verna', 'Toyota Fortuner',
       'Mahindra Bolero Power', 'Tata Zest 90', 'Skoda Rapid Elegance',
       'Tata Vista Quadrajet', 'Chevrolet Beat Diesel',
       'Hyundai Verna 1.4', 'Maruti Suzuki Versa', 'Tata Indigo LX',
       'Volkswagen Vento Konekt', 'Mercedes Benz C', 'Maruti Suzuki Omni',
       'Hyundai Sonata Transform', 'Honda Jazz S', 'Mahindra Scorpio W',
       'Honda Brio V', 'Mahindra TUV300 T8', 'Nissan X Trail',
       'Ford Ikon 1.3', 'Toyota Fortuner 3.0', 'Tata Manza ELAN',
       'Tata zest x', 'Mahindra xyl', 'Mercedes Benz A', 'Tata Indigo LS',
       'Hyundai Verna 1.6', 'BMW 5 Series', 'Skoda Superb 1.8',
       'Audi Q3 2.0', 'Ford Figo Duratorq', 'Mahindra Logan Diesel',
       'Tata Nano GenX', 'Honda City SV', 'Ford Figo Petrol',
       'Toyota Corolla H2', 'Hyundai Xcent Base',
       'Hyundai Accent Executive', 'Tata Zest XE', 'Mahindra XUV500 W6',
       'Tata Tigor Revotron', 'Maruti Suzuki 800', 'Honda Mobilio S',
       'Tata Indica', 'Honda Brio VX', 'Tata Nano Lx', 'Jaguar XE XE',
       'Hyundai Xcent S', 'Hyundai Eon Magna', 'Hyundai Eon D',
       'Maruti Suzuki Estilo', 'Mahindra Scorpio Vlx',
       'Mitsubishi Lancer 1.8', 'Ford Fiesta SXi', 'Audi A6 2.0',
       'Hyundai Getz Prime', 'Hyundai Santro', 'Chevrolet Beat PS',
       'BMW X1 xDrive20d', 'Tata Nano', 'Chevrolet Cruze LTZ',
       'Mahindra XUV500 W10', 'Hyundai Accent GLE', 'Force Motors One',
       'Datsun Go Plus', 'Chevrolet Spark 1.0', 'Renault Duster 85PS',
       'Chevrolet Enjoy', 'Jeep Wrangler Unlimited', 'Hyundai Verna VGT',
       'Maruti Suzuki Celerio', 'Tata Zest Quadrajet', 'Hyundai i10 Era',
       'Tata Indigo Marina', 'Hyundai Xcent SX', 'Tata Nano LX',
       'Mahindra Xylo E8', 'Tata Manza Aqua', 'Tata Venture EX',
       'Skoda Octavia Classic', 'Tata indigo 2017', 'Ford Ikon 1.6',
       'Tata indigo', 'Nissan Sunny XL', 'Volkswagen Polo Trendline',
       'Hyundai Elantra 1.8', 'Jaguar XF 2.2', 'Audi Q5 2.0',
       'BMW X1 sDrive20d', 'Maruti Suzuki S',
       'Volkswagen Vento Comfortline', 'Mahindra KUV100',
       'Volkswagen Jetta Comfortline', 'Volvo S80 Summum', 'BMW X1',
       'Renault Duster RxL', 'Honda WR V', 'Mahindra Scorpio LX',
       'Audi A3 Cabriolet', 'Hyundai Santro AE', 'Tata ZEST 6',
       'Mahindra Xylo D2', 'Hyundai Getz GLE', 'Nissan Micra XL',
       'Chevrolet Tavera LS', 'Tata Tiago Revotron',
       'Tata Tiago Revotorq', 'Tata Nexon', 'Tata', 'Ford Fusion 1.4',
       'Fiat Linea Emotion', 'Tata Sumo Grande',
       'Volkswagen Polo Highline1.2L', 'Maruti Ertiga showroom',
       'Maruti Suzuki swift', 'Hyundai Creta', 'Tata Bolt XM',
       'Hyundai Venue', 'Renault Lodgy', 'Ford Endeavor 4x4',
       'Mahindra Logan', 'Chevrolet Sail 1.2', 'Tata Manza',
       'Toyota Etios G', 'Toyota Qualis', 'Mahindra Quanto C4',
       'Hyundai i20 Select', 'Hyundai Getz', 'Skoda Fabia',
       'Tata Zest XM'], dtype=object)

### Taking company column

In [23]:
df['company'].value_counts()

company
Maruti        216
Hyundai       133
Mahindra       80
Tata           70
Honda          52
Toyota         37
Chevrolet      34
Renault        27
Ford           27
Volkswagen     18
Skoda          10
Audi           10
BMW             8
Datsun          7
Nissan          6
Mercedes        6
Mitsubishi      5
Mini            3
Hindustan       3
Fiat            3
Force           2
Jaguar          2
Land            1
Jeep            1
Volvo           1
Name: count, dtype: int64

In [24]:
df = df[~df['company'].isin(['sell', 'Sale','Used','URJENT','very','Well','all','scratch','urgent','sell','Swift'])]

In [25]:
df= df[~df['company'].str.isnumeric()]

In [26]:
df.shape

(762, 6)

In [27]:
df['company'] = df['company'].str.lower()

In [28]:
df['company'] = df['company'].str.capitalize()

In [29]:
df.head()

                     name   company  year          Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007         80,000  45,000 kms    Petrol
1     Mahindra Jeep CL550  Mahindra  2006       4,25,000      40 kms    Diesel
2      Maruti Suzuki Alto    Maruti  2018  Ask For Price  22,000 kms    Petrol
3       Hyundai Grand i10   Hyundai  2014       3,25,000  28,000 kms    Petrol
4  Ford EcoSport Titanium      Ford  2014       5,75,000  36,000 kms    Diesel

### Taking year column

In [30]:
df.year.dtype
# Here you can see the year column is in object datatype so we have to change it

dtype('O')

In [31]:
df.year.unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '150k', '2003', '2004', '/-Rs', 'sale', '1995', 'ara)', '2002',
       '2001', 'odel', '2 bs', 'emi', 'car', 'digo', 'e...', 'd...',
       'o...', 'cab'], dtype=object)

In [32]:
df = df[df['year'].str.isnumeric()]

In [33]:
df['year'] = df['year'].astype('int')

In [34]:
df.shape

(748, 6)

In [35]:
df.head()

                     name   company  year          Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007         80,000  45,000 kms    Petrol
1     Mahindra Jeep CL550  Mahindra  2006       4,25,000      40 kms    Diesel
2      Maruti Suzuki Alto    Maruti  2018  Ask For Price  22,000 kms    Petrol
3       Hyundai Grand i10   Hyundai  2014       3,25,000  28,000 kms    Petrol
4  Ford EcoSport Titanium      Ford  2014       5,75,000  36,000 kms    Diesel

### Taking Price column

In [36]:
df['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [37]:
df['Price'].isnull().sum()

np.int64(0)

In [38]:
df['Price'] = df['Price'].replace('Ask For Price', np.nan)

df['Price'] = (
    df['Price']
    .str.replace(',', '', regex=False)
    .astype('Int64')
)

In [39]:
# import seaborn as sns
# sns.distplot(df['Price'])

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 748 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        748 non-null    object
 1   company     748 non-null    object
 2   year        748 non-null    int64
 3   Price       727 non-null    Int64
 4   kms_driven  748 non-null    object
 5   fuel_type   745 non-null    object
dtypes: Int64(1), int64(1), object(4)
memory usage: 41.6+ KB

### Taking kms_driven column

In [41]:
df['kms_driven']

0        45,000 kms
1            40 kms
2        22,000 kms
3        28,000 kms
4        36,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 748, dtype: object

In [42]:
df = df[~df['kms_driven'].str.isalpha()]

In [43]:
df['kms_driven'] = df['kms_driven'].str.split(' ').str.get(0).str.replace(',','').astype('int')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 746 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        746 non-null    object
 1   company     746 non-null    object
 2   year        746 non-null    int64
 3   Price       725 non-null    Int64
 4   kms_driven  746 non-null    int64
 5   fuel_type   745 non-null    object
dtypes: Int64(1), int64(2), object(3)
memory usage: 41.5+ KB

### Taking fule_type column

In [45]:
df['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [46]:
df['fuel_type'].isnull().sum()

np.int64(1)

In [47]:
df['fuel_type'] = df['fuel_type'].fillna(value=df['fuel_type'].mode()[0])

In [48]:
df['fuel_type'].isnull().sum()

np.int64(0)

In [49]:
df.to_csv(r'C:\Users\mabin\Desktop\DataScienceClassNotes\MLOps_Project_1\ml_ops_project_-_1\data\processed\Cleaned_car_dataset.csv', index=False)